webpackConfig: ./webpack/webpack.dev.js

environment:
  STAGE: dev
  IS_LOCAL_DEV: 1
  REGION: ${opt:region, self:provider.region}
  NODE_ENV: 'development'

  # TODO: Override this params with a local DB
  # DATABASE
  DB_HOST: 'dev-backoffice-db.cecvssvzpdup.us-east-1.rds.amazonaws.com'
  DB_PORT: 3306
  DB_SCHEMA: 'backoffice_db_dev'
  DB_USER: 'backoffice_db_user_dev'
  DB_PASSWORD: 'PYxf3AB9857SLAdJ'

  # OMNIPAY
  OMNIPAY_ENDPOINT: 'https://dev-pay.omni.cr'
  OMNIPAY_AUTH_URL: 'https://omnipay-dev.auth.us-east-1.amazoncognito.com/oauth2/token'
  OMNIPAY_CLIENT_ID: '3fh8ndptkja5itsmsqu4aejam3'
  OMNIPAY_SECRET_KEY: '1r3ifdjmb72aamdfhhuvvua01h13772jovf65qh4l6bukbeet01v'
  OMNIPAY_SCOPE: 'https://pay.omni.cr/card-wallet.read'

  # Redis
  # REDIS_URI: ${ssm:smps-${opt:stage, self:provider.stage}-redis}

  # PROVIDERS
  OMNIPAY_SERVICE_URL: https://dev-bo-pay.omni.cr
  SUPERAPP_SERVICE_URL: https://dev-api-admin-taxi.superapphub.com

  # SQS
  MERCHANTS_QR_GENERATOR_QUEUE_NAME: 'sqs-merchants-qr-generator-dev'

  # Cognito agents pool
  COGNITO_POOL_ID: us-east-1_1C23CUTlo

ProviderARNs:
  AGENTS_POOL: arn:aws:cognito-idp:us-east-1:863348442394:userpool/us-east-1_1C23CUTlo

vpc:
  securityGroupIds:
    - sg-0789f99a7fb16f151

  subnetIds:
    - subnet-00ce4ca7c2f9a1884
    - subnet-02d485bc77c8c3178
    - subnet-050dc8fffbb6ae0d6

customDomain:
  domainName: dev-api-qr-merchants.superbackoffice.com
  basePath: ''
  stage: ${opt:stage, self:provider.stage}
  createRoute53Record: true

resourcePolicy:
  - Effect: Allow
    Principal: '*'
    Action: execute-api:Invoke
    Resource:
      - execute-api:/*/*/*
    Condition:
      IpAddress:
        aws:SourceIp:
          - '0.0.0.0/0'
